### ISSUE TITLE
Excessive CPU/RAM usage

### ISSUE THREAD

**Issue by IscoV** [node-cron/node-cron#358] opened 2022-07-01 07:59 UTC
Hello, here is my problem.

I am new to using node-cron, I scheduled the task correctly and checked that it works correctly. The problem is in the excessive use of CPU/RAM that node-cron generates and it collapses the VPS server where it is stored.

Attached image

![image](https://user-images.githubusercontent.com/53531688/176851045-0134bb97-4ee3-4fb5-a5ce-57b1539d769c.jpeg)

Although the CPU usage looks low, it increases over time.

All this when the script is started and kept active with pm2

If anyone knows anything about this or how to mediate excessive resource usage, I would be grateful.

**Comment by supercoffee** [comment] 2022-07-12 17:46
I'm seeing similar behavior using node-cron 3.0.1.  The worker script runs out of memory, crashes, and restarts about twice an hour. 

Here's the snippet of code I'm using to set up my cron jobs:

```typescript
cron.schedule('0 9 * * 1', async () => {
    console.log('Running weekly report job');
    await weeklyReportJob.run();
}, {
    timezone: process.env.APP_TIMEZONE
});

// monthly on the first
cron.schedule('0 13 1 * *', async () => {
    console.log('Running billing report job');
    await billingReportJob.run();
}, {
    timezone: process.env.APP_TIMEZONE
});
```

<img width="1232" alt="Screen Shot 2022-07-12 at 10 40 16 AM" src="https://user-images.githubusercontent.com/3880240/178557613-b7668ddc-408f-48ae-9f7b-a1368ab2742b.png">

Other info:
Node cron: 3.0.1
Node version: 16
Typescript version: 4.6.4
Note: production version is compiled with tsc to run in pure JS

**Comment by joekuo77** [comment] 2022-07-14 06:29
I think maybe some memory leak in 3.0.1
down-grade to 3.0.0 (no change other code)  then ..solved....

**Comment by michaelheller-md** [comment] 2022-07-18 07:40
We also faced problems in 3.0.1 regarding increased memory consumption. About 150MB more memory was used by our services. Downgrading to version 3.0.0 again solved the issue.

**Comment by ahkay** [comment] 2022-07-19 06:39
We had the same problem, ram usage increased by about 10mb per minute, crashing our express.js server after 6 hrs. This was replicated locally and occurred even with an empty service running. Downgrading to 3.0.0 solved it.

**Comment by gokulchandra** [comment] 2022-07-21 10:30
I faced a similar issue. And noticed that once I removed a timezone specification the RAM usage was stable. 
Here's a screenshot of my metrics.

![node-cron](https://user-images.githubusercontent.com/13641098/180192218-342dbd77-e7fa-4ef4-a3e9-7272048429d3.png)

I did notice that the [timematcher](https://github.com/node-cron/node-cron/compare/v3.0.0...v3.0.1#diff-df4c11dadbec75a53f295ed4b8b300b9becbe80eaab000f832b2115b279b4a3cL35) implementation was updated between the versions to get rid of the moment dependency.

I might need to spend some more time investigating the cause.

Other info:
Node cron: 3.0.1
Node version: 16
Typescript version: 4.7.4 (tranpiled to JS)

**Comment by supercoffee** [comment] 2022-07-21 21:23
@gokulchandra  In my testing the memory leak only happens when a timezone is set.  Without a timezone, there is no memory leak (at least for as long I monitored it).

**Comment by supercoffee** [comment] 2022-07-21 21:31
@gokulchandra Good observation about the time matcher.  I looked through the diffs myself a while back and noticed that too but I didn't think much of it.  After searching for "intl datetimeformat memory leak", I found this [old Github issue](https://github.com/nodejs/node/issues/31914) in Node itself about that specific function causing a memory leak.  It seems relevant, but the issue is now closed and the fix was rolled out in v12.20.0 according to [this comment.](https://github.com/nodejs/node/issues/31914#issuecomment-751410474)

**Comment by gokulchandra** [comment] 2022-07-22 15:22
Created a PR with a possible solution here: https://github.com/node-cron/node-cron/pull/366

**Comment by gokulchandra** [comment] 2022-07-22 23:29
#366 should handle this.

**Comment by ruettenm** [comment] 2022-08-31 07:19
@merencia could you please have a look?

**Comment by IscoV** [comment] 2022-09-03 09:55
@merencia If you are really considering dropping moment.js as a dependency, as even lighter (2Kb) alternative with timezone support I would recommend DayJS.

[Timezones DayJS](https://day.js.org/docs/en/plugin/timezone)

I suggest it in case at some point you plan to change it.

**Comment by damienbry** [comment] 2022-10-08 10:06
@supercoffee thanks for pointing that out, in my case **removing the timezone** solved my R14 heroku alerts

<img width="574" alt="Capture d’écran 2022-10-08 à 12 06 30" src="https://user-images.githubusercontent.com/8018715/194702222-eec0a274-3ee1-46f6-a717-5d99c010f37f.png">

**Comment by ruettenm** [comment] 2022-10-21 08:37
@merencia or @t-bonatti - could you please have a look or hand over the maintenance of the package?

**Comment by m-emre-yalcin** [comment] 2022-11-01 17:31
removing the timezone option is fixing it, thanks

**Comment by net-tech** [comment] 2022-11-08 02:51
Any fix for this other than removing timezone?

**Comment by net-tech** [comment] 2022-11-10 14:16
Does anyone know which Timezone is used if no timezone option is provided?

**Comment by oigeen** [comment] 2022-11-21 01:58
> Does anyone know which Timezone is used if no timezone option is provided?

I would assume it uses UTC by default

**Comment by net-tech** [comment] 2022-11-21 23:09
I ended up switching to [croner](https://www.npmjs.com/package/croner).

**Comment by Mati365** [comment] 2022-12-13 12:35
It's a shame that a lib that is used by more than 60,000 other packages has such a critical problem and the author doesn't even bother to merge a ready fix...

**Comment by Tanner-Scadden** [comment] 2023-04-29 01:33
Is there any possibility this was fixed? This caused a slow leak while I was out of town and I got a massive bill because of it.

**Comment by ghostebony** [comment] 2023-04-29 09:49
@Tanner-Scadden use this patch for now

```patch
diff --git a/src/time-matcher.js b/src/time-matcher.js
index 52a0b8ea5db9914d7e7b7ef74f8da9c8fcdbc181..6f24160a528c799a43fea4f415237b6597918723 100644
--- a/src/time-matcher.js
+++ b/src/time-matcher.js
@@ -15,6 +15,18 @@ class TimeMatcher{
         this.pattern = convertExpression(pattern);
         this.timezone = timezone;
         this.expressions = this.pattern.split(' ');
+        this.dtf = this.timezone
+            ? new Intl.DateTimeFormat('en-US', {
+                year: 'numeric',
+                month: '2-digit',
+                day: '2-digit',
+                hour: '2-digit',
+                minute: '2-digit',
+                second: '2-digit',
+                hourCycle: 'h23',
+                fractionalSecondDigits: 3,
+                timeZone: this.timezone
+            }) : null;
     }
 
     match(date){
@@ -31,20 +43,8 @@ class TimeMatcher{
     }
 
     apply(date){
-        if(this.timezone){
-            const dtf = new Intl.DateTimeFormat('en-US', {
-                year: 'numeric',
-                month: '2-digit',
-                day: '2-digit',
-                hour: '2-digit',
-                minute: '2-digit',
-                second: '2-digit',
-                hourCycle: 'h23',
-                fractionalSecondDigits: 3,
-                timeZone: this.timezone
-            });
-            
-            return new Date(dtf.format(date));
+        if(this.dtf){
+            return new Date(this.dtf.format(date));
         }
         
         return date;
```

**Comment by Aaqu** [comment] 2023-05-26 07:26
same problem with node-corn 3.0.2

**Comment by nolimitdev** [comment] 2023-11-02 11:45
CONER https://www.npmjs.com/package/croner seems to be much better alternative

**Closed** 2023-11-08 14:01 UTC
