### ISSUE TITLE
Node-cron sometimes misses execution when seconds are specified

### ISSUE THREAD

**Issue by zenonpelle** [node-cron/node-cron#38] opened 2016-12-14 15:40 UTC
The check interval fore something to run is 1000 ms. Thats why you sometimes miss an execution if second is specified.
If you change to 500 ms between checks and also check if the task is run for the specified code below. I think it will work fine.
Added in task.js:
  function isAlreadyRun(date, lastDate){
    if (lastDate){
      return (
        (date.getSeconds() === lastDate.getSeconds())&&
        (date.getMinutes() === lastDate.getMinutes())&&
        (date.getHours() === lastDate.getHours())&&
        (date.getDate() === lastDate.getDate())&&
        (date.getMonth() === lastDate.getMonth())&&
        (date.getDay() === lastDate.getDay()));
    }else{
      return false;
    }
  }
and changed update function:
  Task.prototype.update = function(date){
    if(mustRun(this, date)&& !isAlreadyRun(date,this.lastDate)){
      try {
        this.lastDate = date;
        this.execution();
      } catch(err) {
        console.error(err);
      }
    }
  };

**Comment by JPinSPACE** [comment] 2017-03-11 15:20
I can confirm this. Additionally, if seconds are not specified it looks like it defaults to `0`, so seconds are actually always specified.

This problem is leading to a significant number of missed firings in our application. I agree that it would be safer to have the task know when it should fire next and then check if the time is past that and if it has already fired. Relying on a JavaScript timeout firing in a one second window is too prone to error.

**Comment by manojchandrashekar** [comment] 2017-05-23 07:13
I'm curious to know how the system-level cron handles such a scenario. I'm guessing there is enough overheard for a few milliseconds there also.

**Comment by merencia** [comment] 2018-09-10 12:38
fixed at https://github.com/merencia/node-cron/pull/80

**Comment by tremendus** [comment] 2018-10-08 15:41
I would like to reopen this issue. It appears to not be resolved according to the following reproducible issue:

```
const cron = require('node-cron')
const jobCounts = [ 0, 0, 0, 0, 0, 0, 0, 0 ]
function startJob (i) {
  new cron.schedule('*/3 * * * * *', function () { /* eslint-disable-line */
    jobCounts[i]++
    console.log(new Date().getSeconds(), i, jobCounts[i])
  })
}
jobCounts.forEach((val, i) => {
  startJob(i)
})
```

The first 30 or so cycles work fine, but somewhere around cycle 30-35, cron starts either adding or missing jobs: 
```
// ... everything fine so far ... 
5 2 30
45 0 30
45 4 30
45 5 30
45 6 30
45 3 30
45 7 30
45 1 30

48 1 31
48 0 31
48 5 31
48 6 31
48 3 31
48 2 31
48 7 31
48 4 31

51 4 32
51 0 32
51 5 32 <- job #5 runs @:51s past the min
51 6 32
51 3 32
51 2 32
51 1 32
51 7 32
51 5 33 <- whoops, already did job #5 @:51s past the min

54 2 33
54 4 33
54 0 33
54 5 34
54 6 33
54 3 33
54 1 33
54 7 33

57 0 34
57 5 35
57 6 34
57 3 34
57 1 34
57 7 34
57 2 34
57 4 34
```

And things continue to deteriorate from there.

**Comment by merencia** [comment] 2018-10-09 18:03
hello @tremendus I think I found the problem... I have fixed that in this pull request: https://github.com/node-cron/node-cron/pull/116

This is your script running for test:
![image](https://user-images.githubusercontent.com/1686635/46688720-77e80600-cbd4-11e8-9f89-ca814e567f3d.png)

**Comment by TDola** [comment] 2018-10-10 15:04
I am confirming this issue with version 2.0.3.  Double and triple execution actually seems to norm now if the system is at all busy.
I made a schedule to run every minute, the system is very busy every 15 minutes.  9:46 duplicating lines up with the increased usage, 9:56 and 9:57 is a quiet time, 10:00 is super busy (like 12 cores 100% busy).  It appears to be almost random.

```

2018-10-10 09:46:00:872
2018-10-10 09:46:00:919
2018-10-10 09:46:00:950
2018-10-10 09:47:00:436
2018-10-10 09:47:00:608
2018-10-10 09:48:00:295
2018-10-10 09:49:00:904
2018-10-10 09:50:00:922
2018-10-10 09:51:00:454
2018-10-10 09:52:00:329
2018-10-10 09:53:00:128
2018-10-10 09:54:00:909
2018-10-10 09:55:00:723
2018-10-10 09:56:00:380
2018-10-10 09:56:00:536
2018-10-10 09:56:00:724
2018-10-10 09:57:00:179
2018-10-10 09:57:00:273
2018-10-10 09:58:00:976
2018-10-10 09:59:00:805
2018-10-10 10:00:00:900
2018-10-10 10:01:00:790
2018-10-10 10:02:00:907
2018-10-10 10:03:00:987
```

**Comment by TDola** [comment] 2018-10-10 16:22
I see missed executions a lot if the system gets busy.  The timeout method doesn't have the ability to check all previous schedules and run them.  You would need to use something like performance.now() and compare each tick to see how many 1000 MS have passed, then run the update on each one in turn.

**Comment by merencia** [comment] 2018-10-11 19:31
@TDola I think the problem here is the same that https://github.com/node-cron/node-cron/issues/120, right?

**Comment by TDola** [comment] 2018-10-11 19:46
@merencia yep, the same issue, i started A new issue instead of resurrecting this one

**Comment by merencia** [comment] 2018-10-11 19:47
so, I will close this issue in favor of #120

**Closed by merencia** 2018-10-11 19:47 UTC
Labels: bug, must be done
